import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {snapshot,agentPolicy} from '../capabilities/policy.mjs';import {CapabilityJobs} from '../capabilities/jobs.mjs';
const run=promisify(execFile);
async function fixture(t){const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'devspace-capability-test-')));t.after(()=>fs.rm(root,{recursive:true,force:true}));const project=path.join(root,'source');await fs.mkdir(project);await fs.writeFile(path.join(project,'hello.py'),'print("hello")');return {root,project};}
test('snapshot excludes credentials and tool configuration and rejects symlinks',async t=>{const {root,project}=await fixture(t);await fs.writeFile(path.join(project,'.env'),'TOKEN=fixture');await fs.mkdir(path.join(project,'.codex'));await fs.writeFile(path.join(project,'.codex/config.toml'),'untrusted');const target=path.join(root,'copy');const r=await snapshot(project,target);assert.equal(r.count,1);await assert.rejects(fs.stat(path.join(target,'.env')));await fs.symlink('/etc/passwd',path.join(project,'escape'));await assert.rejects(snapshot(project,path.join(root,'copy2')),/符号链接/);});
test('kernel boundary permits task files, denies outside reads/writes and symlink escapes', {skip:process.platform!=='darwin'},async t=>{const {root,project}=await fixture(t),home=path.join(root,'home'),tmp=path.join(root,'tmp');await fs.mkdir(home);await fs.mkdir(tmp);const outside=path.join(root,'secret');await fs.writeFile(outside,'fixture');await fs.symlink(outside,path.join(project,'escape'));const binary=await fs.realpath(process.execPath),sb=path.join(root,'worker.sb');await fs.writeFile(sb,agentPolicy({workspace:project,home,tmp,binary,proxyPort:65432}));const code=`const fs=require('fs'),net=require('net'),r={};for(const [key,p] of [['outside',${JSON.stringify(outside)}],['symlink',${JSON.stringify(path.join(project,'escape'))}]]){try{fs.readFileSync(p);r[key]=true}catch(e){r[key]=false}}try{fs.writeFileSync(${JSON.stringify(outside)},'changed');r.write=true}catch{r.write=false}fs.writeFileSync(${JSON.stringify(path.join(project,'ok'))},'ok');const s=net.connect(443,'1.1.1.1');s.on('connect',()=>{r.network=true;s.destroy();console.log(JSON.stringify(r))});s.on('error',()=>{r.network=false;console.log(JSON.stringify(r))});`;const r=await run('/usr/bin/sandbox-exec',['-f',sb,binary,'-e',code]);assert.deepEqual(JSON.parse(r.stdout),{outside:false,symlink:false,write:false,network:false});assert.equal(await fs.readFile(outside,'utf8'),'fixture');});
test('jobs cannot change execution policy; retry IDs deduplicate and source remains untouched',async t=>{const {root,project}=await fixture(t),configPath=path.join(root,'config.json');await fs.writeFile(configPath,JSON.stringify({enabled:true,codex:true,projects:[project]}));let calls=0;const jobs=new CapabilityJobs({root:path.join(root,'runtime'),configPath,grants:async()=>({grants:[{path:project,mode:'rw'}]}),runner:async({workspace})=>{calls++;await fs.writeFile(path.join(workspace,'result.txt'),'result');return {exitCode:0,events:[{type:'turn.completed'}],stderr:'',modelRequests:0};}});await jobs.init();const a={requestId:'bounded-test-01',kind:'codex.develop',project,prompt:'test'};await assert.rejects(jobs.dispatch('task_submit',{...a,sandbox:'danger-full-access'}));await jobs.dispatch('task_submit',a);await jobs.dispatch('task_submit',a);while(jobs.active.size)await new Promise(r=>setTimeout(r,5));assert.equal(calls,1);assert.equal((await jobs.result(a.requestId)).state,'needs_review');await assert.rejects(fs.stat(path.join(project,'result.txt')));await assert.rejects(jobs.dispatch('task_submit',{...a,prompt:'other'}));await assert.rejects(jobs.dispatch('task_artifact',{requestId:a.requestId,path:'../job.json'}));assert.equal((await jobs.dispatch('task_artifact',{requestId:a.requestId,path:'result.txt'})).content,'result');});
test('revoking a project stops a running job and prevents reading its artifacts',async t=>{
 const {root,project}=await fixture(t),configPath=path.join(root,'config.json');await fs.writeFile(configPath,JSON.stringify({enabled:true,codex:true,projects:[project]}));let allowed=true;
 const jobs=new CapabilityJobs({root:path.join(root,'runtime'),configPath,grants:async()=>({grants:allowed?[{path:project,mode:'rw'}]:[]}),runner:({signal})=>new Promise(resolve=>signal.addEventListener('abort',()=>resolve({exitCode:null,reason:'cancelled',events:[],stderr:'',modelRequests:0}),{once:true}))});await jobs.init();await jobs.dispatch('task_submit',{requestId:'revoke-running-01',kind:'codex.develop',project,prompt:'test'});allowed=false;
 await new Promise(resolve=>setTimeout(resolve,1200));assert.equal(jobs.active.size,0);await assert.rejects(jobs.dispatch('task_result',{requestId:'revoke-running-01'}),/授权已撤销/);
});
import {startModelProxy} from '../capabilities/model-proxy.mjs';
test('model relay denies unknown callers, models and remote built-in tools before forwarding',async t=>{
 const {root}=await fixture(t),authFile=path.join(root,'auth.json');await fs.writeFile(authFile,JSON.stringify({auth_mode:'chatgpt',tokens:{access_token:'fake-test-only',account_id:'fake-account'}}));const relay=await startModelProxy({model:'test-model',authFile});t.after(()=>relay.close());const url='http://127.0.0.1:'+relay.port+'/v1/responses';
 assert.equal((await fetch(url,{method:'POST',body:'{}'})).status,403);
 for(const data of [{model:'other'},{model:'test-model',background:true},{model:'test-model',tools:[{type:'web_search'}]}])assert.equal((await fetch(url,{method:'POST',headers:{Authorization:'Bearer '+relay.nonce},body:JSON.stringify(data)})).status,400);
});
test('continuation uses sealed output, keeps the original untouched and detects source drift',async t=>{
 const {root,project}=await fixture(t),configPath=path.join(root,'config.json');await fs.writeFile(configPath,JSON.stringify({enabled:true,codex:true,projects:[project]}));let turn=0;
 const jobs=new CapabilityJobs({root:path.join(root,'runtime'),configPath,grants:async()=>({grants:[{path:project,mode:'rw'}]}),runner:async({workspace})=>{const p=path.join(workspace,'new.txt');if(turn++===0)await fs.writeFile(p,'first');else await fs.writeFile(p,(await fs.readFile(p,'utf8'))+' second');return {exitCode:0,events:[{type:'turn.completed'}],stderr:'',modelRequests:0};}});await jobs.init();const wait=async()=>{while(jobs.active.size)await new Promise(r=>setTimeout(r,5));};
 await jobs.dispatch('task_submit',{requestId:'continue-parent',kind:'codex.develop',project,prompt:'first'});await wait();await fs.writeFile(path.join(root,'runtime/jobs/continue-parent/workspace/new.txt'),'late mutation');
 await jobs.dispatch('task_continue',{requestId:'continue-child',parentId:'continue-parent',prompt:'continue'});await wait();assert.equal((await jobs.dispatch('task_artifact',{requestId:'continue-child',path:'new.txt'})).content,'first second');assert.equal((await jobs.dispatch('task_changes',{requestId:'continue-child'})).changes[0].kind,'modify');await assert.rejects(fs.stat(path.join(project,'new.txt')));
 await fs.writeFile(path.join(project,'hello.py'),'changed by user');await assert.rejects(jobs.dispatch('task_continue',{requestId:'continue-drift',parentId:'continue-child',prompt:'continue'}),/发生变化/);
});
