import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import http from 'node:http';
const realBase=path.join(os.homedir(),'.local/share/devspace-air');
const fixture=await fs.mkdtemp(path.join(os.tmpdir(),'devspace-http-'));
process.env.DEVSPACE_HOME=fixture;
await fs.mkdir(path.join(fixture,'app'),{recursive:true});
await fs.writeFile(path.join(fixture,'app/package.json'),'{}');
await fs.symlink(path.join(realBase,'app/node_modules'),path.join(fixture,'app/node_modules'));
const {createManager}=await import('../src/server.mjs');
const {atomicJSON}=await import('../src/store.mjs');
const {stageGeneration}=await import('../src/policy.mjs');
after(()=>fs.rm(fixture,{recursive:true,force:true}));
test('manager enforces launch token, origin, session, CSRF and frame isolation',async t=>{
  const initial=await stageGeneration([],{template:'(version 1)\n(deny default)\n; ACCESS_GRANTS',baseConfig:{}});
  await atomicJSON(path.join(fixture,'config/access/active.json'),{revision:initial.revision});
  const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
  let controlCalls=0;
  const manager=createManager({port,assistant:{snapshot:async()=>({version:'test'}),action:async()=>{controlCalls++;return 'ok';}},supervisor:{state:async()=>({service:{running:false,loaded:false},tunnel:{running:false},telemetry:null,busy:false})},transactions:{recover:async()=>{}},picker:async()=>({cancelled:true})});
  const server=await manager.start();t.after(()=>manager.close());
  const origin='http://127.0.0.1:'+port;
  assert.equal(server.address().address,'127.0.0.1');
  let r=await fetch(origin+'/api/state');assert.equal(r.status,401);
  r=await fetch(origin+'/api/cli');assert.equal(r.status,401);
  const badHostStatus=await new Promise((resolve,reject)=>{const q=http.get(origin+'/health',{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);});q.on('error',reject);});assert.equal(badHostStatus,403);
  r=await fetch(origin+'/internal/launch',{method:'POST',headers:{'x-launch-secret':'wrong'}});assert.equal(r.status,403);
  r=await fetch(origin+'/internal/launch',{method:'POST',headers:{'x-launch-secret':manager.launchSecret}});
  const url=(await r.json()).url,token=new URL(url).hash.slice('#launch='.length);
  r=await fetch(origin+'/api/session',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:JSON.stringify({token})});assert.equal(r.status,403);
  r=await fetch(origin+'/api/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({token})});
  assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/Max-Age=0/);
  const session=await r.json(),authorization='Bearer '+session.accessToken,csrf=session.csrf;
  r=await fetch(origin+'/api/cli/enabled',{method:'POST',headers:{Authorization:authorization,Origin:origin,'Content-Type':'application/json'},body:'{"enabled":false}'});assert.equal(r.status,403);
  r=await fetch(origin+'/api/cli/enabled',{method:'POST',headers:{Authorization:authorization,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':csrf},body:'{"enabled":false}'});assert.equal(r.status,200);assert.equal(JSON.parse(await fs.readFile(path.join(fixture,'config/cli-access.json'),'utf8')).enabled,false);
  r=await fetch(origin+'/api/assistant/action',{method:'POST',headers:{Authorization:authorization,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({action:'probe'})});assert.equal(r.status,403);assert.equal(controlCalls,0);
  r=await fetch(origin+'/api/assistant',{headers:{Authorization:authorization}});assert.equal((await r.json()).version,'test');
  r=await fetch(origin+'/api/assistant/action',{method:'POST',headers:{Authorization:authorization,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({action:'probe'})});assert.equal(r.status,202);assert.equal(controlCalls,1);
  r=await fetch(origin+'/api/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({token})});assert.equal(r.status,401);
  r=await fetch(origin+'/api/state',{headers:{Authorization:authorization}});assert.equal(r.status,200);assert.equal((await r.json()).grants.length,0);
  r=await fetch(origin+'/api/pick-folder',{method:'POST',headers:{Authorization:authorization,Origin:origin,'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,403);
  r=await fetch(origin+'/api/pick-folder',{method:'POST',headers:{Authorization:authorization,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':csrf},body:'{}'});assert.deepEqual(await r.json(),{cancelled:true});
  r=await fetch(origin+'/');assert.equal(r.headers.get('x-frame-options'),'DENY');assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('access-control-allow-origin'),null);
});
test('idle manager exits without stopping DevSpace, but not while picker is open',async t=>{
  let now=1000,exited=false,stops=0;
  const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
  const manager=createManager({port,clock:()=>now,idleMs:100,idleSweepMs:10,onIdle:()=>{exited=true;},
    supervisor:{state:async()=>({service:{running:true},tunnel:{running:true},busy:false}),stop:async()=>{stops++;}},
    transactions:{recover:async()=>{}},
    picker:({signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('cancelled'),{name:'AbortError'}))))});
  await manager.start();t.after(()=>manager.close());
  const origin='http://127.0.0.1:'+port;
  let r=await fetch(origin+'/internal/launch',{method:'POST',headers:{'x-launch-secret':manager.launchSecret}});
  const nonce=new URL((await r.json()).url).hash.slice('#launch='.length);
  r=await fetch(origin+'/api/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({token:nonce})});
  const session=await r.json(),authorization='Bearer '+session.accessToken,csrf=session.csrf;
  const headers={Authorization:authorization,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':csrf};
  const pending=fetch(origin+'/api/pick-folder',{method:'POST',headers,body:'{}'});
  await new Promise(r=>setTimeout(r,30));now=1200;
  await new Promise(r=>setTimeout(r,30));assert.equal(exited,false);
  await fetch(origin+'/api/cancel-picker',{method:'POST',headers,body:'{}'});
  assert.deepEqual(await (await pending).json(),{cancelled:true});
  now=1400;await new Promise(r=>setTimeout(r,40));
  assert.equal(exited,true);assert.equal(stops,0);
});
test('a cookie captured by another loopback port cannot recover or exercise manager authority',async t=>{
 let now=1000,calls=0;
 const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
 const manager=createManager({port,clock:()=>now,assistant:{snapshot:async()=>({ok:true}),action:async()=>{calls++;return 'ok';}},transactions:{recover:async()=>{}}});await manager.start();t.after(()=>manager.close());
 const origin='http://127.0.0.1:'+port;
 const launch=async()=>{const r=await fetch(origin+'/internal/launch',{method:'POST',headers:{'x-launch-secret':manager.launchSecret}});return new URL((await r.json()).url).hash.slice('#launch='.length);};
 const exchange=nonce=>fetch(origin+'/api/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({token:nonce})});
 const nonce=await launch(),login=await exchange(nonce),issued=await login.json();
 const cookie='dsa_session='+(issued.accessToken||login.headers.get('set-cookie').split(';')[0].split('=')[1]);
 assert.equal((await fetch(origin+'/api/session',{headers:{Cookie:cookie,Origin:origin}})).status,401);
 assert.equal((await fetch(origin+'/api/assistant/action',{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':issued.csrf},body:'{"action":"probe"}'})).status,401);assert.equal(calls,0);
 assert.equal(typeof issued.accessToken,'string');assert.ok(!login.headers.get('set-cookie')?.includes(issued.accessToken));
 const auth={Authorization:'Bearer '+issued.accessToken},write={...auth,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':issued.csrf};
 assert.equal((await fetch(origin+'/api/session',{headers:auth})).status,200);
 assert.equal((await fetch(origin+'/api/session',{headers:{Authorization:'Bearer invalid'}})).status,401);
 assert.equal((await fetch(origin+'/api/assistant',{headers:{...auth,Origin:'http://127.0.0.1:1'}})).status,403);
 assert.equal((await exchange(nonce)).status,401);
 now=900999;assert.equal((await fetch(origin+'/api/assistant',{headers:auth})).status,200);
 now=901001;assert.equal((await fetch(origin+'/api/assistant',{headers:auth})).status,401);
 const fresh=await (await exchange(await launch())).json();const freshAuth={Authorization:'Bearer '+fresh.accessToken};
 now=1500000;assert.equal((await fetch(origin+'/api/activity',{method:'POST',headers:{...freshAuth,Origin:origin,'Content-Type':'application/json','X-CSRF-Token':fresh.csrf},body:'{}'})).status,200);
 now=1801002;assert.equal((await fetch(origin+'/api/session',{headers:freshAuth})).status,200);
 now=2400001;assert.equal((await fetch(origin+'/api/session',{headers:freshAuth})).status,401);
 const expired=await launch();now+=60001;assert.equal((await exchange(expired)).status,401);
});
