import {StringDecoder} from 'node:string_decoder';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {agentPolicy,digest} from './policy.mjs';import {startModelProxy} from './model-proxy.mjs';
export async function runGrok({root,workspace,prompt,model='grok-4.6',runtime,signal,onSpawn=()=>{},timeoutMs=600000}){
 const binary=runtime?.grokBinary||await fs.realpath(process.env.GROK_BINARY||path.join(os.homedir(),'.grok/bin/grok'));
 if(runtime?.grokHash&&digest(await fs.readFile(binary))!==runtime.grokHash)throw Error('Grok运行程序已变化，需要重新核验');
 const home=path.join(root,'grok-home'),tmp=path.join(root,'tmp');await fs.mkdir(path.join(home,'.grok'),{recursive:true});await fs.mkdir(tmp,{recursive:true});const diagnostics=[];const proxy=await startModelProxy({provider:'grok',model,maxRequests:25,onDiagnostic:e=>diagnostics.push(e)});
 const config=`[cli]\nuse_leader = false\n[model.devspace]\nmodel = ${JSON.stringify(model)}\nbase_url = "http://127.0.0.1:${proxy.port}/v1"\nenv_key = "DEVSPACE_AGENT_TOKEN"\nmax_completion_tokens = 4096\n[models]\ndefault = "devspace"\n`;
 await fs.writeFile(path.join(home,'.grok/config.toml'),config,{mode:0o600});const node=runtime?.node||process.execPath,sb=path.join(root,'grok-policy.sb');await fs.writeFile(sb,agentPolicy({workspace,home,tmp,binary,helpers:[node,path.join(path.dirname(node),'npm'),path.join(path.dirname(path.dirname(node)),'lib/node_modules/npm/bin/npm-cli.js')],readRoots:[path.dirname(path.dirname(node))],proxyPort:proxy.port}));
 const args=['-I',fileURLToPath(new URL('./resource-wrapper.py',import.meta.url)),'/usr/bin/sandbox-exec','-f',sb,binary,'-p',prompt,'--model','devspace','--cwd',workspace,'--output-format','streaming-json','--max-turns','12','--no-subagents','--no-plan','--disable-web-search','--tools','run_terminal_cmd,read_file,grep,list_dir,search_replace','--allow','Bash','--allow','Read','--allow','Edit','--allow','Write','--allow','Grep','--sandbox','off'];
 let stderr='',output='',exitCode,reason=null;const events=[],decoder=new StringDecoder('utf8');
 try{await new Promise(resolve=>{const child=spawn('/usr/bin/python3',args,{cwd:workspace,detached:true,stdio:['ignore','pipe','pipe'],env:{HOME:home,PATH:path.dirname(node)+':/Library/Developer/CommandLineTools/usr/bin:/usr/bin:/bin',TMPDIR:tmp,DEVSPACE_AGENT_TOKEN:proxy.nonce,LANG:'en_US.UTF-8',TERM:'dumb',npm_config_ignore_scripts:'true',npm_config_audit:'false',npm_config_fund:'false'}});onSpawn(child.pid);const stop=r=>{reason??=r;try{process.kill(-child.pid,'SIGTERM');}catch{};const t=setTimeout(()=>{try{process.kill(-child.pid,'SIGKILL');}catch{}},1000);t.unref();};const abort=()=>stop('cancelled');signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();const timer=setTimeout(()=>stop('timeout'),timeoutMs);child.stdout.on('data',b=>{output+=decoder.write(b);if(Buffer.byteLength(output)>2000000)stop('output_limit');});child.stderr.on('data',b=>stderr=(stderr+b.toString()).slice(-12000));child.on('error',e=>stderr=e.message);child.on('close',code=>{output+=decoder.end();exitCode=code;clearTimeout(timer);signal?.removeEventListener('abort',abort);resolve();});});
 let text='';for(const line of output.split('\n')){try{const e=JSON.parse(line);if(e.type==='text')text+=e.data||'';if(e.type==='end'){events.push({type:e.stopReason==='end_turn'?'turn.completed':'turn.failed',usage:e.usage});}if(e.type==='result'){events.push({type:e.is_error?'turn.failed':'turn.completed'});text+=typeof e.result==='string'?e.result:'';}}catch{}}if(text)events.push({type:'item.completed',item:{type:'agent_message',text}});
 return {exitCode,reason,stderr,events,modelRequests:proxy.calls(),diagnostics};}finally{await proxy.close();}
}
